import { SignOutButton, SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { api, RouterOutputs } from "~/utils/api";
import dayjs from 'dayjs'
import relativeTime from "dayjs/plugin/relativeTime";
import { LoadingPage } from "~/components/loading";
dayjs.extend(relativeTime);


const CreatePostWizard = () => {
  const { user } = useUser()
  if (!user) return null

  return (
    <div className="flex gap-3 m-2 p-1">
      <Image
        src={user.imageUrl}
        className="h-14 w-14 rounded-full"
        alt={`@${user.username}'s profile picture`}
        width={56}
        height={56}
      />
      <input placeholder="Input some emojis" className="grow bg-transparent outline-none" />

    </div>
  )
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number]
const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (

    <div className="flex p-8 border-b border-slate-400 p-4 gap-3">
      <Image
        src={author.profileImageUrl}
        className="h-14 w-14 rounded-full"
        alt={`@${author.username}'s profile picture`}
        width={56}
        height={56}
      />
      <div className="flex flex-col">
        <div className="flex text-slate-300 font-semibold gap-1">
          <span>{`@ ${author.username}`}</span>

          <Link href={`/post/${post.id}`}>
            <span className="font-thin">{` · ${dayjs(
              post.createdAt
            ).fromNow()}`}</span>
          </Link>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  )
}

const Feed = () => {

  const { data, isLoading } = api.posts.getAll.useQuery()

  if (isLoading) return <LoadingPage />
  if (!data) return <div>Could not load feed</div>
  return (
    <div className="flex flex-col">
      {
        [...data, ...data]?.map((fullPost) => (
          <PostView {...fullPost} key={fullPost.post.id} />
        ))
      }
    </div>
  )
}

const Home: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn } = useUser()
  // start fetching the posts asap
  api.posts.getAll.useQuery()

  if (!userLoaded) return <div />
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="md:max-w-2xl w-full border-x border-slate-100/10 h-full">
          <div className="border-b border-slate-100/10 p-4 flex">

            {!isSignedIn && <SignInButton />}
            {!!isSignedIn && <SignOutButton />}
          </div>
          <div>
            {
              !!isSignedIn && <CreatePostWizard />
            }
            <Feed />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
